### ISSUE TITLE
Difference between docs/jekyll-theme and src/jekyll-theme?

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/npm-publish-scripts#12]
I noticed (and was confused by) two `jekyll-theme` directories. One's under `docs/` and the other is under `src/`. They seem to be have similar/identical contents.

I'm assuming that `docs/` is for first-party documentation for the `npm-publish-scripts` project, and `src/` is the general templates for third-party projects that use this package, but why the duplication of `jekyll-theme/`? Can `npm-publish-scripts` just pull the Jekyll stuff from `src/jekyll-theme/` when it needs to document itself?

**Comment by gauntface** [comment]
That actually needs some fixing.

What is published to NPM from this project isn't what is in src/, there is a build step to handle the CSS variables in browsers that don't support them.

docs/jekyll-theme/ should be using that "built" version.

**Comment by gauntface** [comment]
Fixed now.
