### ISSUE TITLE
Should the release branch be kept following publication?

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/npm-publish-scripts#21]
The current publication process creates a new `release` branch in the project. You can see this with https://github.com/GoogleChrome/sw-toolbox/tree/release

The auto-tagging is done against this branch, e.g.: https://github.com/GoogleChrome/sw-toolbox/releases/tag/v3.3.0

This branch is kept following the publication.

I'm not sure whether it can be safely deleted or not, given that there's a tag against it. If it needs to stick around, then we should find some way of letting folks know not to delete it—maybe renaming it `release-do-not-delete` or something?

As it is, there's a big temptation to delete it to get the GitHub web UI to stop pestering about filing a PR:
![image](https://cloud.githubusercontent.com/assets/1749548/18724121/40d678d6-8009-11e6-899c-739fcbcfc907.png)

**Comment by gauntface** [comment]
Altered this so tags are done against master.
